# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j

qos: das-preempt
account: das
partition: das
exclude: null

timeout_min: 5760
array_parallelism: 8

nodes: ${train.num_nodes}
tasks_per_node: ${train.devices}
gres: gpu:rtx_3090:${train.devices}
cpus_per_task: 6
mem_gb: ${eval:'int(30*${train.devices})'}

name: ${hydra.job.name}

signal_delay_s: 120
max_num_timeout: 0

additional_parameters: { "mail-user": "anon", "mail-type": "BEGIN,END,FAIL" }