# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j

qos: icis-preempt
account: icis
partition: icis
exclude: null

timeout_min: 5760
array_parallelism: 8

nodes: ${train.num_nodes}
tasks_per_node: ${train.devices}
gres: gpu:rtx_a6000:${train.devices}
cpus_per_task: 16
mem_gb: ${eval:'int(60*${train.devices})'}

name: ${hydra.job.name}

signal_delay_s: 120
max_num_timeout: 0

additional_parameters: { "mail-user": "nvaessen", "mail-type": "BEGIN,END,FAIL" }