defaults:
  - _self_
  - data/set: ls960h
  - data/pipe: asr
  - decoder: default
  - network: base_asr
  - optim/algo: adam
  - optim/schedule: tri_stage
  - train: asr
  - log: default

# project settings
project_name: 'nanow2v2-asr'
use_wandb: true

# use torch compile
compile: false

# tag to add to the experiment dashboard for easy filtering
# of certain experiment
date_tag: ${now:%Y-%m-%d}
tags: null

# whether to log all train predictions to file
save_all_train_predictions: false

# choose if train/eval is done
fit_model: true
eval_model: true

# load from an initial checkpoint
load_from_ckpt: null

# we dynamically decide on the run_id, which will also be used as the log folder and PWD at runtime
run_id: ${get_run_id:}
sweep_id: ${now:%Y-%m-%d}---${now:%H-%M-%S}

slurm_job_id: ${oc.env:SLURM_ARRAY_JOB_ID,${oc.env:SLURM_JOB_ID, null}}
slurm_array_task_id: ${oc.env:SLURM_ARRAY_TASK_ID, null}

hydra:
  job:
    chdir: true
  run:
    dir: outputs/asr/run/${run_id}
  sweep:
    dir: outputs/asr/sweep/${sweep_id}
    subdir: ${hydra.job.num}
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback